[package]
name = "rust-webgame-project"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
strum = "0.24"
strum_macros = "0.24"
rand = "0.4"

[[bin]]
name = "main"
path = "src/logic/main.rs"